### ISSUE TITLE
Feature Request:  Add Ability to Batch Process STIX & CybOx XML

### ISSUE THREAD

**Issue by packet-rat** [Soltra/cti-stats#1]
In addition to ability to query TAXII Servers, add the ability to batch process STIX & CybOx XML files.  

Basis:  Have many STIX files that cannot be successfully consumed/parsed and/or are only partially consumed/parsed.

Conceptually one would select/specify a root folder which would be used to iterate though all subfolders/files containing valid structure.

Additional Features:

(1) Ability to aggregate on Namespaces
(2) Ability to map/record Nesting
(3) Ability to measure embedded/external Reference

**Comment by treyka** [comment]
Roger that, @packet-rat, will address this issue first thing in the morning. Dunno about all your additional feature requests, but at least recursively ingesting a directory structure containing stix/cybox xml is easily doable.

**Comment by treyka** [comment]
@packet-rat Done and done! ^_^

**Comment by packet-rat** [comment]
Many Thanks Trey! - 

There were two reasons for suggesting inclusion of NameSpaces:

(1) It will prevent skewing of statistics if we collectively process the same content (i.e.:  For example many of us process the same STIX/CybOX Packages from DHS/US-CERT/NCCIC).  Similarly you could get 10,000s of duplicates from folks processing HAIL-A-TAXII, and other common OSI feeds.

(2) It could help those of us processing large amounts of feeds in our Dev Labs to analyze differences/similarities between various Producers, Trending, etc.

If incorporated, it might require an option to do a one way hash of the NameSpaces as direct attribution could be problematic for some of us.

**Comment by treyka** [comment]
@packet-rat I recognize that many groups are consuming some of the same datasets (ie, the NCCIC reports). Unfortunately, in order to record the object ids (using the hashing approach you suggested) would result in extremely voluminous reporting output (estimated on the order of >=10000x the current report size). So while *ideally* we'd have a mechanism to dedupe the aggregated reporting data, I don't think that is in fact practical.

Regardless of the fact that there will inevitably be duplicate data across all the submitted reports, if we see that organizations A, B, and C have x number / percentage of a certain object type (and, perhaps more importantly, report no/low usage of certain object types!) that information is extremely helpful to informing how we focus our refactoring efforts.

Feel free to continue the discussion here but unless I'm convinced it's critical to address, I won't attempt to deduplicate aggregated reporting data. (Note that cti-stats *does* dedupe reporting data within a *single* reporting organization!)
